### ISSUE TITLE
Service Intent must be explicit

### ISSUE THREAD

**Issue by tonespy** [wso2-attic/product-emm#194]
I keep getting this

```
 FATAL EXCEPTION: main
                                                                Process: org.wso2.emm.agent, PID: 26299
                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wso2.emm.agent/org.wso2.emm.agent.ServerDetails}: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=org.wso2.emm.system.service.START_SERVICE }
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
                                                                    at android.os.Handler.dispatchMessage(Handler.java)
                                                                    at android.os.Looper.loop(Looper.java)
                                                                    at android.app.ActivityThread.main(ActivityThread.java)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
                                                                 Caused by: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=org.wso2.emm.system.service.START_SERVICE }
                                                                    at android.app.ContextImpl.validateServiceIntent(ContextImpl.java)
                                                                    at android.app.ContextImpl.startServiceCommon(ContextImpl.java)
                                                                    at android.app.ContextImpl.startService(ContextImpl.java)
                                                                    at android.content.ContextWrapper.startService(ContextWrapper.java)
                                                                    at org.wso2.emm.agent.utils.CommonUtils.callSystemApp(CommonUtils.java:265)
                                                                    at org.wso2.emm.agent.ServerDetails.onCreate(ServerDetails.java:70)
                                                                    at android.app.Activity.performCreate(Activity.java)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java) 
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java) 
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java) 
                                                                    at android.os.Looper.loop(Looper.java) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
```

You were pointing to `org.wso2.emm.system.service.START_SERVICE` and there's no directory with `org.wso2.emm.system` they all are `org.wso2.emm.agent`

**Comment by kasundananjaya** [comment]
WSO2 EMM Agent and system-service are two different apps. System service is only applicable to COPE mode where you have to sign this app with device firmware signing key. You should get above exception because you must have tried an operation which requires system level access. If you need device owner level operations (or activate Android for work) please read : https://docs.wso2.com/display/IoTS300/Device+Ownership+Application

**Comment by tonespy** [comment]
Yeah. About darn time. Gave up on your platform a long about the same time I posted this and built mine.
